const dayOptions = document.querySelectorAll("#day-options button");
const helpOptions = document.querySelectorAll("#help-options button");
const badOptions = document.querySelectorAll("#bad-options button");

function chooseOption(options) {
    options.forEach(function(button) {

        button.addEventListener("click", function() {

            options.forEach(function(item) {
                item.classList.remove("selected");
            });

            button.classList.add("selected");
        });

    });
}

chooseOption(dayOptions);
chooseOption(helpOptions);
chooseOption(badOptions);


const makeSignal = document.querySelector("#make-signal");
const signal = document.querySelector("#signal");

const dayAnswer = document.querySelector("#day-answer");
const helpAnswer = document.querySelector("#help-answer");
const badAnswer = document.querySelector("#bad-answer");


function getAnswer(options) {

    for (let i = 0; i < options.length; i++) {

        if (options[i].classList.contains("selected")) {
            return options[i].textContent.trim();
        }

    }

    return "";
}


makeSignal.addEventListener("click", function() {

    const day = getAnswer(dayOptions);
    const help = getAnswer(helpOptions);
    const bad = getAnswer(badOptions);

    if (day === "" || help === "" || bad === "") {

        alert("Please answer all three questions first.");
        return;

    }

    dayAnswer.textContent = day;
    helpAnswer.textContent = help;
    badAnswer.textContent = bad;

    signal.classList.remove("hidden");

    signal.scrollIntoView({
        behavior: "smooth"
    });

});


const words = document.querySelector("#words");
const makeAiSignal = document.querySelector("#make-ai-signal");

const aiResult = document.querySelector("#ai-result");

const aiDay = document.querySelector("#ai-day");
const aiHelp = document.querySelector("#ai-help");
const aiBad = document.querySelector("#ai-bad");


makeAiSignal.addEventListener("click", async function() {

    const text = words.value.trim();

    if (text === "") {

        alert("Tell us what you're experiencing first.");
        return;

    }

    try {

        const response = await fetch(
            "http://localhost:3000/generate-signal",
            {
                method: "POST",

                headers: {
                    "Content-Type": "application/json"
                },

                body: JSON.stringify({
                    words: text
                })
            }
        );

        const data = await response.json();

        if (!response.ok) {

            alert(data.error);
            return;

        }

        aiDay.textContent = data.day;
        aiHelp.textContent = data.help;
        aiBad.textContent = data.bad;

        aiResult.classList.remove("hidden");

        aiResult.scrollIntoView({
            behavior: "smooth"
        });

    // } catch (error) {

    //     console.error(error);

    //     alert("Something went wrong. Please try again.");

    // }

    }catch (error) {

    console.error(error);

    aiDay.textContent =
        "AI personalization is currently unavailable.";

    aiHelp.textContent =
        "You can still use your words to create a support signal.";

    aiBad.textContent =
        "No information was generated by AI.";

    aiResult.classList.remove("hidden");

    aiResult.scrollIntoView({
        behavior: "smooth"
    });

}

});

const copySignal = document.querySelector("#copy-signal");
const copyMessage = document.querySelector("#copy-message");

copySignal.addEventListener("click", async function() {

    const signalText =
        "MY SIGNAL\n\n" +
        "When I'm having a difficult day:\n" +
        dayAnswer.textContent.trim() + "\n\n" +
        "What helps me:\n" +
        helpAnswer.textContent.trim() + "\n\n" +
        "What doesn't help:\n" +
        badAnswer.textContent.trim();

    try {

        await navigator.clipboard.writeText(signalText);

        copyMessage.textContent = "Your signal has been copied!";

    } catch (error) {

        console.error(error);

        copyMessage.textContent =
            "Unable to copy your signal.";

    }

});

const shareSignal = document.querySelector("#share-signal");
const shareMessage = document.querySelector("#share-message");

shareSignal.addEventListener("click", async function() {

    const signalText =
        "MY SIGNAL\n\n" +
        "When I'm having a difficult day:\n" +
        dayAnswer.textContent.trim() + "\n\n" +
        "What helps me:\n" +
        helpAnswer.textContent.trim() + "\n\n" +
        "What doesn't help:\n" +
        badAnswer.textContent.trim();

    if (navigator.share) {

        try {

            await navigator.share({
                title: "MySignal",
                text: signalText
            });

        } catch (error) {

            console.log("Share cancelled.");

        }

    } else {

        try {

            await navigator.clipboard.writeText(signalText);

            shareMessage.textContent =
                "Sharing isn't supported here, so your signal was copied instead.";

        } catch (error) {

            shareMessage.textContent =
                "Unable to share your signal.";

        }

    }

});

const resetSignal = document.querySelector("#reset-signal");

resetSignal.addEventListener("click", function() {

    dayOptions.forEach(function(button) {
        button.classList.remove("selected");
    });

    helpOptions.forEach(function(button) {
        button.classList.remove("selected");
    });

    badOptions.forEach(function(button) {
        button.classList.remove("selected");
    });

    words.value = "";

    signal.classList.add("hidden");
    aiResult.classList.add("hidden");

    copyMessage.textContent = "";
    shareMessage.textContent = "";

    document.querySelector("#create").scrollIntoView({
        behavior: "smooth"
    });

});

window.addEventListener("load", function() {
    words.value = "";
});